backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
media_folder: "img" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Příspěvky" # Used in the UI
    sort: "date:desc" # Default is title:asc
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Rozložení", name: "layout", widget: "hidden", default: "post"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Podnadpis", name: "subtitle", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Datum zveřejnění", name: "date", widget: "datetime"}
      - {label: "Štítky", name: "tags", widget: "list", default: ["Mládež"], required: false}
      - {label: "Úvodní obrázek", name: "header-img", widget: "image", required: false}
      - {label: "Obsah", name: "body", widget: "markdown"}
      - {label: "Styl záhlaví", name: "header-style", widget: "hidden", default: "text"}
      - {label: "Jazyk", name: "lang", widget: "hidden", default: "cs"}

      